- README.md
> docs: updated readme w latest iOS local setup

- src/components/common/CustomPicker.res
- src/components/common/DynamicFields.res
- src/pages/payment/Card.res
- src/types/RequiredFieldsTypes.res
Fixed Card holder name not getting displayed and custom picker should pick initial value even if not present in the list
> fix: fixed name not displaying and custom picker should pick initial value

- src/components/elements/ModalHeader.res
- src/routes/ParentPaymentSheet.res
- src/types/SdkTypes.res
fixed payment sheet header text 
fixed saved payment method screen header text
> fix: fixed payment sheet and saved payment screen modal texts

- src/pages/payment/SaveCardsList.res
- src/types/SdkTypes.res
displayDefaultSavedPaymentIcon prop added
> feat: displayDefaultSavedPaymentIcon prop added

- src/components/common/CustomButton.res
- src/components/elements/ButtonElement.res
- src/components/modules/ApplePayButtonView.res
Added React Native Component for ApplePay Button 
Added Special Condition to display the button (workaround)
> feat: apple pay native view

- index.web.js
- spelling correction in props for webUI.
> refactor(web-ui): fixed initial props spelling for webApp

- src/components/elements/ButtonElement.res
removed hardcoded setup_future usage and customer_acceptance from wallet's confirm body
> refactor: refactored save wallet logic

- src/components/common/DynamicFields.res
- src/types/RequiredFieldsTypes.res
- src/utility/reusableCodeFromWeb/LocaleString.res
```
- Empty email: "Email cannot be empty"
- Invalid email: "Invalid email address"
- Empty Cardholder Name: "Card Holder's name is required"
- Invalid Cardholder Name: "Last Name required"
```
> fix: fix error description on input fields

- src/components/elements/ButtonElement.res
- src/headless/HeadlessUtils.res
- src/hooks/AllPaymentHooks.res
- src/hooks/LoggerHook.res
- src/pages/payment/Redirect.res
- src/pages/payment/SavedPaymentScreen.res
- src/types/PaymentMethodListType.res
- src/types/RequiredFieldsTypes.res
- src/types/Types.res
- src/utility/logics/PaymentUtils.res
- src/utility/logics/ProcessPaymentRequest.res
- src/utility/logics/Utils.res
- Added support for input type `BlikCode`.
- Added util `getDictFromArray` and function `getIndexZeroAndApplyTransform` in `Redirect.res` to eliminate code repetition.
- Changed input field type form `string` to `enum` of type `Email | Country | Name | Bank | BlikCode`.
> refactor: added utils and functions to remove repetition

- src/routes/App.res
- src/routes/NavigatorRouter.res
- src/routes/NavigatorRouterParent.res
- src/types/SdkTypes.res
- src/utility/reusableCodeFromWeb/ErrorHooks.res
- Wrapped `NavigatorRouter` with a parent component to completely sperate-out the "Payment Method Management" flow.
- support for `ephemeralKey` & Sdk-state `PaymentsMethodManagement`.
> feat: router for payment method management

- package.json
- reactNativeWeb/webpack.config.js
This will enable hot reloading for react-native web
> feat: hot reloading for web

- src/utility/reusableCodeFromWeb/LocaleString.res
- Locale for card label in polish.
[Slack issue link](https://juspay.slack.com/archives/C065UPRTBQX/p1727424901429079)
> docs: update polish locale for cardholder nickname

- src/components/elements/ModalHeader.res
- src/components/modules/HyperModule.res
- src/hooks/AllPaymentHooks.res
- src/pages/paymentMethodsManagement/PaymentMethodListItem.res
- src/pages/paymentMethodsManagement/PaymentMethodsManagement.res
- src/routes/PMMangementNavigatorRouter.res
> fix: ui and config for pmm

- src/components/elements/ModalHeader.res
| Before                                                                                                                                            | After                                                                                                                                             |
|---------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------|
| <img width="350" alt="Screenshot 2024-10-03 at 5 08 38 PM" src="https://github.com/user-attachments/assets/0beac259-f587-404b-8334-bf5e7afb556a"> | <img width="350" alt="Screenshot 2024-10-03 at 5 08 …
> fix: modal header UI

- server.js
- api endpoint in demo server to replicate s2s call for payment method management.
> feat: added api in demo server to replicate s2s call for pmm

- src/pages/payment/NickNameElement.res
- Show validation error on-blur of nickname input field.
> fix: validation errors on blur for nickname

- src/components/common/CustomView.res
- src/components/elements/ConfirmButton.res
- src/contexts/ViewportContext.res
- src/routes/App.res
- src/routes/FullScreenSheetWrapper.res
- src/routes/GlobalConfirmButton.res
- Bottom padding inconsistency in scrollview.
> fix: padding in scrollview bottomsheet

- src/pages/payment/NickNameElement.res
- Card's nickname getting changed to _no-name_ when user sends empty string in Nickname field.
| Saved Card initially (abc VISA card)                                                                                                                | Submit save card with empty nickname                                                                                                                | Nickname Changed to empty string                                                                                                                    |
|-----------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------ …
> fix: no change in nickname if user send empty string in nickname field

- src/pages/payment/NickNameElement.res
- remove leading spaces on nickname input field.
> fix: remove leading spaces on nickname input field

- src/components/elements/CardSchemeComponent.res
- src/components/elements/PaymentSheetUi.res
- src/components/elements/ScanCardButton.res
- src/types/LoggerTypes.res
- Logs for co-badged card scheme feature
> feat: logs for co-badged feature

- .github/CODEOWNERS
Added codeowners for mandatory reviews
> Add CODEOWNERS for mandatory reviews

- .github/workflows/build_and_test_android.yml
- .github/workflows/build_and_test_ios.yml
- Add `DETOX_SENTRY_DSN` to github action variables.
> chore: update sentry dsn for detox tests
